# Example usage
First things first, let's import the libraries.

In [1]:
import numpy as np
import igraph as ig

from onion_decomposition import od

## Karate Club network
Note that `od.compute(m)` outputs `corelist` first, followed by `layerlist`.

In [2]:
g = ig.load('dataset/karate.gml')
m = np.array(g.get_adjacency().data)

We now obtain the adjacency matrix (as a `numpy.ndarray`) that acts as the input for the function `od.compute`.

In [3]:
m

array([[0, 1, 1, ..., 1, 0, 0],
       [1, 0, 1, ..., 0, 0, 0],
       [1, 1, 0, ..., 0, 1, 0],
       ...,
       [1, 0, 0, ..., 0, 1, 1],
       [0, 0, 1, ..., 1, 0, 1],
       [0, 0, 0, ..., 1, 1, 0]])

Now, the onion decomposition goes:

In [4]:
od.compute(m)

(array([4, 4, 4, 4, 3, 3, 3, 4, 4, 2, 3, 1, 2, 4, 2, 2, 2, 2, 2, 3, 2, 2,
        2, 3, 3, 3, 2, 3, 3, 3, 4, 3, 4, 4]),
 array([7, 6, 7, 6, 3, 3, 3, 5, 6, 2, 3, 1, 2, 6, 2, 2, 2, 2, 2, 3, 2, 2,
        2, 4, 3, 3, 2, 4, 3, 3, 5, 4, 5, 5]))

## Stochastic Block Model generated network
Note that `od.compute(m)` outputs `corelist` first, followed by `layerlist`.

In [5]:
g = ig.load('dataset/sbm_n_100-q_2-eps_0.1-c_3.0.gml')
m = np.array(g.get_adjacency().data)
od.compute(m)

(array([1, 2, 1, 1, 2, 1, 2, 1, 2, 2, 1, 2, 2, 2, 1, 2, 2, 2, 2, 1, 2, 2,
        2, 2, 1, 2, 2, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 1, 2,
        2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 1, 1, 1, 2, 2, 2, 2, 1, 1, 2, 2, 2,
        2, 1, 2, 2, 2, 1, 1, 2, 2, 2, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 1,
        2, 2, 2, 1, 1, 2, 2, 2, 2, 2, 2, 1]),
 array([ 2, 16,  1,  1, 14,  1,  4,  1,  3,  4,  1,  3,  6,  3,  1,  4,  8,
         3,  5,  1, 14, 13,  3,  3,  1, 16, 17, 12,  4,  1,  3,  3, 13,  4,
         5,  1,  1,  9, 17,  8,  7, 10,  1, 11, 15, 10,  2,  9,  3, 10,  5,
        13, 12,  3,  1,  1,  1, 11, 10,  4, 12,  2,  1,  4,  6,  6,  3,  1,
         4,  5,  7,  1,  1,  3,  5, 11,  1,  3, 10,  8,  7,  9,  3,  5,  3,
         4,  3,  1,  3, 12,  3,  1,  1,  5, 13,  6,  3,  9,  3,  2]))