In [20]:
import numpy as np
import graph_tool.all as gt

In [206]:
g = gt.collection.data["karate"]
m = gt.adjacency(g)
m = np.array(m.todense())

In [207]:
m

array([[0., 1., 1., ..., 1., 0., 0.],
       [1., 0., 1., ..., 0., 0., 0.],
       [1., 1., 0., ..., 0., 1., 0.],
       ...,
       [1., 0., 0., ..., 0., 1., 1.],
       [0., 0., 1., ..., 1., 0., 1.],
       [0., 0., 0., ..., 1., 1., 0.]])

In [208]:
OD(m)

(array([4., 4., 4., 4., 3., 3., 3., 4., 4., 2., 3., 1., 2., 4., 2., 2., 2.,
        2., 2., 3., 2., 2., 2., 3., 3., 3., 2., 3., 3., 3., 4., 3., 4., 4.]),
 array([7., 6., 7., 6., 3., 3., 3., 5., 6., 2., 3., 1., 2., 6., 2., 2., 2.,
        2., 2., 3., 2., 2., 2., 4., 3., 3., 2., 4., 3., 3., 5., 4., 5., 5.]))

In [210]:
# read SBM
g = gt.load_graph("/Users/tzuchi/Workspace/research/bp_active/input/N_100-Q_2-method_cab_ec-eps_0.1-c_3.0-0.00675571392128.gml")
m = gt.adjacency(g)
m = np.array(m.todense())

In [211]:
OD(m)

(array([1., 2., 1., 1., 2., 1., 2., 1., 2., 2., 1., 2., 2., 2., 1., 2., 2.,
        2., 2., 1., 2., 2., 2., 2., 1., 2., 2., 2., 2., 1., 2., 2., 2., 2.,
        2., 1., 1., 2., 2., 2., 2., 2., 1., 2., 2., 2., 1., 2., 2., 2., 2.,
        2., 2., 2., 1., 1., 1., 2., 2., 2., 2., 1., 1., 2., 2., 2., 2., 1.,
        2., 2., 2., 1., 1., 2., 2., 2., 1., 2., 2., 2., 2., 2., 2., 2., 2.,
        2., 2., 1., 2., 2., 2., 1., 1., 2., 2., 2., 2., 2., 2., 1.]),
 array([ 2., 16.,  1.,  1., 14.,  1.,  4.,  1.,  3.,  4.,  1.,  3.,  6.,
         3.,  1.,  4.,  8.,  3.,  5.,  1., 14., 13.,  3.,  3.,  1., 16.,
        17., 12.,  4.,  1.,  3.,  3., 13.,  4.,  5.,  1.,  1.,  9., 17.,
         8.,  7., 10.,  1., 11., 15., 10.,  2.,  9.,  3., 10.,  5., 13.,
        12.,  3.,  1.,  1.,  1., 11., 10.,  4., 12.,  2.,  1.,  4.,  6.,
         6.,  3.,  1.,  4.,  5.,  7.,  1.,  1.,  3.,  5., 11.,  1.,  3.,
        10.,  8.,  7.,  9.,  3.,  5.,  3.,  4.,  3.,  1.,  3., 12.,  3.,
         1.,  1.,  5., 13.,  6.,  3.,  

In [176]:
def OD(mat):
    m, n = mat.shape
    assert m == n, "Adjacency matrix must be square"
    assert np.array_equal(mat, mat.transpose()), "Adjaceny matrix must be symmetric"
    deg = np.resize(np.sum(mat, 0), m).astype(int)
    core = layer = 1
    
    unexplored_vtx = np.full(m, True)
    
    corelist = np.zeros(m)
    layerlist = np.zeros(m)

    while np.any(unexplored_vtx):
        this_layer = np.full(m, False)
        this_layer = [True if (deg_ <= core and unexplored_vtx[idx]) else False for idx, deg_ in enumerate(deg)]
        for vtx_idx, vtx in enumerate(this_layer):
            if vtx:
                corelist[vtx_idx] = core
                layerlist[vtx_idx] = layer
                for target_vtx_idx, target_vtx in enumerate(mat[vtx_idx]):
                    if target_vtx == 1:
                        deg[target_vtx_idx] -= 1
                unexplored_vtx[vtx_idx] = False
        layer += 1
        deg_for_core = [deg[idx] for idx, d in enumerate(unexplored_vtx) if d]
        if len(deg_for_core) > 0 and min(deg_for_core) >= core + 1:
            core = min(deg_for_core)
            
    return corelist, layerlist


In [183]:
#       9--8--10        11-----      15
#          |            |     |      |
# 0--1--2--3--4--5------6-----7------14
#                       |    / \     |
#                       ----12-13    16
g = gt.Graph()
g.add_edge(0, 1)
g.add_edge(1, 2)
g.add_edge(2, 3)
g.add_edge(3, 8)
g.add_edge(8, 9)
g.add_edge(8, 10)
g.add_edge(3, 4)
g.add_edge(4, 5)
g.add_edge(5, 6)
g.add_edge(6, 11)
g.add_edge(6, 7)
g.add_edge(6, 12)
g.add_edge(11, 7)
g.add_edge(7, 12)
g.add_edge(7, 13)
g.add_edge(12, 13)
g.add_edge(7, 14)
g.add_edge(14, 15)
g.add_edge(14, 16)
g.set_directed(False)

In [185]:
m = gt.adjacency(g)
m = np.array(m.todense())

In [186]:
OD(m)

(array([1., 1., 1., 1., 1., 1., 2., 2., 1., 1., 1., 2., 2., 2., 1., 1., 1.]),
 array([1., 2., 3., 4., 5., 6., 8., 8., 2., 1., 1., 7., 8., 7., 2., 1., 1.]))

In [203]:
#      1-----
#     / \   |
# 4--0---3  |
#     \ /   |
#      2-----

g = gt.Graph()
g.add_edge(0, 1)
g.add_edge(0, 2)
g.add_edge(0, 3)
g.add_edge(0, 4)
g.add_edge(1, 2)
g.add_edge(1, 3)
g.add_edge(2, 3)
g.set_directed(False)


In [204]:
m = gt.adjacency(g)
m = np.array(m.todense())

In [205]:
OD(m)

(array([3., 3., 3., 3., 1.]), array([2., 2., 2., 2., 1.]))

In [201]:
[1, 1, 1, 1, 1, 1, 2, 2, 1, 1, 1, 2, 2, 2, 1, 1, 1] == a

True

In [196]:
layers == b

True